services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    volumes:
      - ./database:/usr/src/app/database
    environment:
      - NODE_ENV=production
    ports:
      - "5000:5000"

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  database:
