services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: timfentoncortina/dermi-mirror-api:latest
    volumes:
      - ./configs:/configs
    environment:
      - NODE_ENV=production
    ports:
      - "5000:5000"

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: timfentoncortina/dermi-mirror-client:latest
    volumes:
      - ./configs:/configs
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  database:
